import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./(contexts)/ThemeProvider";
import NavBar from "./(components)/NavBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <ThemeProvider >
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <NavBar />
          <div className="flex-grow overflow-y-auto bg-page-light dark:bg-page-dark text-default-text-black dark:text-default-text-white">
            {children}
          </div>
        </div>
      </body>
    </ThemeProvider>
  </html>
  );
}
